name: scarf-env
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - python=3.12.3
  - cudatoolkit=11.8.0
  - cuda-nvcc=11.8.89
  - pip
  - pip:
    - torch==2.3.1+cu118
    - torchvision==0.18.1+cu118
    - torchaudio==2.3.1+cu118
    - scanpy==1.11.0
    - scib==1.1.7
    - scikit-learn==1.5.2
    - transformers==4.46.3
    - datasets==2.21.0